# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.20
_src_path: https://github.com/OCA/oca-addons-repo-template.git
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: false
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: Odoo
odoo_version: 16.0
org_name: Odoo Community Association (OCA)Gedeelde Weelde
org_slug: gedeeldeWeelde
rebel_module_groups: []
repo_description: Fields for products sold in supermarkets.
repo_name: Product foor fields
repo_slug: product-food-fields
repo_website: https://github.com/gedeeldeWeelde/product-food-fields
use_pyproject_toml: false
use_ruff: true

